import React from 'react';
import { useImmer } from 'use-immer';

export const useKeyValues = () => {
  const [keyValue, setKeyValue] = useImmer({
    superRight: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    menuLeft: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    metaLeft: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    plate: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    backquote: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyA: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyZ: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    tab: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyQ: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    capsLock: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    shiftLeft: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    space: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    controlLeft: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    altLeft: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    altRight: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    controlRight: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    backslash: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    backspace: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    enter: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    shiftRight: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit1: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit2: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit3: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit4: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit5: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit6: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit7: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit8: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit9: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    digit0: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    minus: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    equal: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyS: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyD: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyF: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyG: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyH: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyJ: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyK: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyL: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    semicolon: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    quote: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyX: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyC: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyV: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyB: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyN: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyM: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    comma: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    period: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    slash: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyW: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyE: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyR: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyT: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyY: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyU: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyI: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyO: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    keyP: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    bracketLeft: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
    bracketRight: {
      color: 'red',
      opacity: 1,
      transparent: true,
      selected: false,
      clearCoat: 0,
      reflectivity: 0,
      transmission: 0,
    },
  });

  return {
    keyValue,
    setKeyValue,
  };
};
